### ISSUE TITLE
文档中存在中文字体时会崩溃...

### ISSUE THREAD

**Issue by zerolee** [casouri/emacs#7]
简单复现
1. 准备一个含有中文字体的文件（我测试了 html，common lisp，elisp）
2. 输入 M-: 执行
```elisp
(progn
  (require 'tree-sitter)
  (tree-sitter-get-parser-create 'tree-sitter-elisp))
```
3. 执行
    ```elisp
    (tree-sitter-node-at (point))
    ```
    `Emacs` 闪退
4. 如果最初的文件里没有中文，在执行上面操作后，在往文件里添加中文，则此时 `Emacs` 不会崩溃，执行结果正常返回。

PS：Common Lisp和  html 的执行过程如下
```elisp
;;; Common Lisp
(progn
  (require 'tree-sitter)
  (tree-sitter-get-parser-create 'tree-sitter-commonlisp))
(tree-sitter-node-at (point))
;;; HTML
(progn
  (require 'tree-sitter)
  (tree-sitter-get-parser-create 'tree-sitter-html))
(tree-sitter-node-at (point))
```
下面是测试文件的内容：
1. Emacs lisp
```elisp
(defun fun ()
  "文档字符串.")
```
2. Common lisp
```lisp
(defun fun ()
  "文档字符串.")
```
3. HTML
```html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8"/>
    <title>文档</title>
  </head>
  <body>
  </body>
</html>

```

系统版本：debian 11，Emacs 为本仓库最新版本，语言定义采用 https://github.com/casouri/tree-sitter-module.git 里的脚本进行的编译：
Html 语言定义：https://github.com/tree-sitter/tree-sitter-html
Emacs Lisp 语言定义：https://github.com/Wilfred/tree-sitter-elisp，
Common Lisp 语言定义：https://github.com/theHamsta/tree-sitter-commonlisp

PS：其他的，暂时没有发现什么问题，运行良好，感谢作者的贡献，希望能够早日合并到 master.

**Comment by casouri** [comment]
感谢测试，写得很详细呢。我推了一个修改，现在应该没问题了。

**Comment by zerolee** [comment]
> 感谢测试，写得很详细呢。我推了一个修改，现在应该没问题了。

感谢，确实没有问题了。
