### ISSUE TITLE
query cpp member function call for fontifying

### ISSUE THREAD

**Issue by xwl** [casouri/emacs#8]
Suppose I have: 

     Foo a;
     a.ok();
     a.x;

I would like to use different faces for "ok" and "x". How could one query to match "ok" here? It seems one could match by grouping "." and field_expression, like this:

      (
       (field_expression operator: ".")
       (field_expression field: (field_identifier) @font-lock-function-name-face)
      )

But doesn't seem to work?

**Comment by casouri** [comment]
`a.ok()` seems to be a method call, maybe the name isn't `field_expression`? You can put the snippet in a cpp file and turn on `tree-sitter-inspect-mode` and observe the actual node type of `a.ok()`. HTH

**Comment by xwl** [comment]
Yes, a.ok() is a method call. Here is the test snip:

    struct Foo
    {
        int x;
        int y;

        void ok()
        {}

    };

    int main(int argc, char *argv[])
    {
        Foo a;
        a.x;
        a.ok();
    }

When I put cursor at "a", "." and "o" from "a.ok" respectively, I got:

     body: (compound_statement (expression_statement (call_expression function: (field_expression argument: (identifier)))))
     function: (field_expression operator: ".")
     function: (field_expression field: (field_identifier))

When I put cursor at "x" from "a.x", I got:

     (field_expression field: (field_identifier))

is my query format correct?

**Comment by casouri** [comment]
I can see that `a.ok()` is in a `call_expression`. I bet that `a.x` cannot be the function field in a `call_expression`. So how about:

```
(call_expression function: (field_expression field: (_) @ok))
(field_expression field: (_) @x)
```

**Comment by xwl** [comment]
Thanks for the hint, now i'm able to achieve it by:

    (call_expression function:                                                      
                     (field_expression argument: (_) @font-lock-variable-name-face))
    (call_expression function:                                                      
                     (field_expression field: (_) @font-lock-function-name-face))
