### ISSUE TITLE
error raised when capture name is neither a face nor a function

### ISSUE THREAD

**Issue by orzechowskid** [casouri/emacs#9]
hello!

I'm attempting to write a major mode based on your tree-sitter work and had a question regarding named captures.  how would I write a query to font-lock a node based on the text of other, unrelated, nodes, e.g.:

> `((call_expression (member_expression ((identifier) @x (#match "foo" @x))) ((args) @font-lock-keyword-face)))`

?  my query is causing `treesit-font-lock-fontify-region` to throw an error here:
```
                (cond ((facep face)
                       (put-text-property start end 'face face))
                      ((functionp face)
                       (funcall face start end node))
                      (t (error "Capture name %s is neither a face nor a function" face)))
```
which is correct - `x` is neither a face nor a function.  but I don't wish to apply font-locking to `@x` at all.  do I need to write a no-op function (e.g. `(defun x (&rest ignored))`) so that `(functionp face)` evaluates to `t`, or is there some other workaround I should use?  (or does this error even need to be thrown at all?)

thanks for all your hard work on treesit - apart from this small issue it's been amazingly smooth to work with so far!

**Comment by casouri** [comment]
That makes sense, I'll remove the line that signals error. BTW, do you know the latest version is on savannah? I haven't updated this mirror for a while. You can get it from the feature/tree-sitter branch on savannah or the official mirror. Here is a starter guide on writing major modes with the latest version:

[guide.zip](https://github.com/casouri/emacs/files/9691731/guide.zip)

**Comment by orzechowskid** [comment]
oh, I was not aware that there was newer code on savannah - I'll base my work on that branch.
